### ISSUE TITLE
display any SVG created on the fly

### ISSUE THREAD

**Issue by guibbv2011** [adept-bits/adept_svg#4]
Hi, I used this project to render qr_code SVG, and it works fine, but I need to modify the live data... and for each one, LiveView recompiles and re-renders the page,

so I reused the read_svg function to get around the need to compile the file:
```
def read_svg(svg) do
    case String.valid?(svg) do
        true -> 
            [_, svg] = String.split(svg, "<svg")
            [svg, _] = String.split(svg, "</svg>")
            Map.put(%{}, "wallet_qr", svg <> "</svg>")
         _ ->
             {:file_error, svg}
    end
end
```
and
```
def render(svg, key \\ "wallet_qr", opts \\ [] ) do
     Adept.Svg.render(read_svg(svg), key, opts )
end
```
In this case, we can now display any SVG created on the fly, I think it might be a good feature for the project

**Comment by boydm** [comment]
So if I read this right, you are creating a dynamic svg, then adding it to the library map, then rendering it.

Is the dynamic svg a one-time use thing or is to be reused again later?

Seems like you could just do this in a LiveView component function and not have to do the work to add it to the library map.

I'll try coming up with an example.

**Comment by boydm** [comment]
In the meantime, my second reaction is that maybe you want a "svg" that instead of storing the raw data, stores a callback anonymous function that you supply that provides the contents of the svg on the fly..

**Comment by guibbv2011** [comment]
Yes, you are right and I have used it this way and another side (standard) too, I will always reuse this function, but, maybe I guess thinking outside the box, customers can create animated SVG easily
